/**
 * Create an invitation to register for a user
 * The process is composed of a hyperlink with the invitation ID associated to an email
 * For security reason the invitation expires after a period
 * 
 * Invoked by AWS SQS (polling) with a batch size 1 to avoid partial failure management
 * For high scalability, this should be revised & implemented.
 * @see https://docs.aws.amazon.com/lambda/latest/dg//with-sqs.html
 */
const aws = require('aws-sdk');
const ddb = new aws.DynamoDB.DocumentClient();
const ses = new aws.SES({ region: 'eu-west-1' });
const oneDay = 86400000;
const thirtyDays = oneDay * 30;


exports.handler = async (event, context) => {
    const message = event.Records[0];
    const content = JSON.parse(message.body);

    if (!("email" in content) || !content.email) {
        throw { error: "invalid email", message: message };
    }

    const invitation = {
        id: message.messageId, // free uuid v4 generated by aws sqs at queuing time
        ...content,
        expiresAt: (new Date().getTime()) + oneDay,
        deleteAt: thirtyDays
    };

    await persist(invitation);
    await send(invitation);

    return;
};

async function persist(invitation) {
    return await ddb.put({
        TableName: "invitations",
        ConditionExpression: "attribute_not_exists(id)",
        Item: invitation
    }).promise();
}

async function send(invitation) {
    const email = {
        Source: "Lobby Citoyen MUSES <ludovic.fleury@muses-lobby-citoyen.org>",
        Destination: {
            ToAddresses: [invitation.email]
        },
        Message: {
            Body: {
                Text: {
                    Charset: "UTF-8",
                    Data: composeEmail(invitation)
                }

            },
            Subject: {
                Charset: "UTF-8",
                Data: "Votre inscription au Lobby citoyen MUSES"
            }
        }
    };


    return await ses.sendEmail(email).promise();
}

function composeEmail(invitation) {
    const text = `Cher(e) adhérent(e),

Le Lobby citoyen est très fier de voir une nouvelle Muse venir l’inspirer !

Par votre soutien, vous nous donnez les moyens d’agir au quotidien pour changer les choses.

Par votre présence, vous renforcez l’indépendance et l’influence de MUSES.

Vous pouvez d'ores et déjà finaliser votre adhésion en créant un espace adhérent personnel : {{LINK}}.

MUSES étant en cours de développement, nous vous remercions de votre indulgence car notre esprit de co-construction s’applique également aux diverses fonctionnalités que nous vous proposons.

Le principe du Lobby citoyen étant de mettre entre vos mains un nouvel outil démocratique, n'hésitez surtout pas à nous faire part de vos propositions à l'adresse contact@muses-lobby-citoyen.org !

Nous tenons à vous remercier chaleureusement pour votre engagement.


Solidairement,
L'équipe de MUSES
`;

    return text.replace('{{LINK}}', 'https://muses-lobby-citoyen.org/inscription?invitation=' + invitation.id);
}