const AWS = require('aws-sdk');
const ddb = new AWS.DynamoDB.DocumentClient();

exports.handler = async (event, context) => {

    const vote = {
        id: context.awsRequestId, // free uuid v4 generated by aws for the request 
        memberId: "",
        proposalId: "",
        submittedAt: new Date().toISOString()
    };

    try {
        await persist(member);
    } catch (error) {
        console.error({ error, member, event, context });
        return response(500, { error: error.message, request: context.awsRequestId });
    }

    return response(201, member);
};

async function persist(member) {
    return await ddb.put({
        TableName: 'members',
        Item: member,
    }).promise();
}

function response(code, body, headers) {
    return {
        statusCode: code,
        body: JSON.stringify(body),
        headers: {
            'Access-Control-Allow-Origin': '*',
        },
    };
}